[project]
name = "local-llms"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
